using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

public static class SceneValidation
{
    private static readonly string[] ScenePaths =
    {
        "Assets/Scenes/MainMenu.unity",
        "Assets/Scenes/WordLevel01.unity",
        "Assets/Scenes/AdjectiveLevel01.unity",
        "Assets/Scenes/IdentifyingColors.unity",
        "Assets/Scenes/NumberLevelUI01.unity",
        "Assets/Scenes/NumberInequalitiesLevel.unity",
        "Assets/Scenes/Cashier.unity",
    };

    public static void ValidateConfiguredScenes()
    {
        var rows = new List<SceneResult>();
        var hasFailure = false;

        foreach (var scenePath in ScenePaths)
        {
            var result = ValidateScene(scenePath);
            rows.Add(result);
            hasFailure |= !result.Passed;
        }

        WriteReport(rows);

        if (hasFailure)
        {
            throw new Exception("One or more configured scenes failed validation.");
        }
    }

    private static SceneResult ValidateScene(string scenePath)
    {
        var result = new SceneResult { Path = scenePath };

        if (!File.Exists(scenePath))
        {
            result.Status = "missing";
            result.Notes = "Scene file is missing.";
            return result;
        }

        try
        {
            var scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
            var roots = scene.GetRootGameObjects();
            var allObjects = roots.SelectMany(EnumerateHierarchy).ToArray();
            var missingScriptObjects = FindMissingScriptObjects(allObjects);

            result.Status = missingScriptObjects.Count == 0 ? "pass" : "warning";
            result.RootObjects = roots.Length;
            result.GameObjects = allObjects.Length;
            result.MissingScripts = missingScriptObjects.Count;
            result.Notes = missingScriptObjects.Count == 0
                ? "Scene opened successfully."
                : "Missing script references: " + string.Join("; ", missingScriptObjects);
        }
        catch (Exception ex)
        {
            result.Status = "failed";
            result.Notes = ex.GetType().Name + ": " + ex.Message.Replace(Environment.NewLine, " ");
        }

        return result;
    }

    private static IEnumerable<GameObject> EnumerateHierarchy(GameObject root)
    {
        yield return root;

        foreach (Transform child in root.transform)
        {
            foreach (var descendant in EnumerateHierarchy(child.gameObject))
            {
                yield return descendant;
            }
        }
    }

    private static List<string> FindMissingScriptObjects(IEnumerable<GameObject> objects)
    {
        var missing = new List<string>();

        foreach (var obj in objects)
        {
            var components = obj.GetComponents<Component>();
            if (components.Any(component => component == null))
            {
                missing.Add(GetHierarchyPath(obj));
            }
        }

        return missing;
    }

    private static string GetHierarchyPath(GameObject obj)
    {
        var names = new Stack<string>();
        var current = obj.transform;

        while (current != null)
        {
            names.Push(current.name);
            current = current.parent;
        }

        return string.Join("/", names);
    }

    private static void WriteReport(IReadOnlyCollection<SceneResult> rows)
    {
        var reportPath = Environment.GetEnvironmentVariable("TWENTYONEVERSE_SCENE_VALIDATION_REPORT");

        if (string.IsNullOrWhiteSpace(reportPath))
        {
            var projectRoot = Directory.GetParent(Application.dataPath).FullName;
            reportPath = Path.Combine(projectRoot, "..", "..", "docs", "inventory", "generated", "unity-scene-validation.md");
        }

        reportPath = Path.GetFullPath(reportPath);
        Directory.CreateDirectory(Path.GetDirectoryName(reportPath));

        var lines = new List<string>
        {
            "# Unity Scene Validation",
            string.Empty,
            "Generated by `SceneValidation.ValidateConfiguredScenes`.",
            string.Empty,
            "| Scene | Status | Root objects | GameObjects | Missing scripts | Notes |",
            "| --- | --- | ---: | ---: | ---: | --- |",
        };

        lines.AddRange(rows.Select(row =>
            $"| `{row.Path}` | {row.Status} | {row.RootObjects} | {row.GameObjects} | {row.MissingScripts} | {row.Notes} |"));

        File.WriteAllLines(reportPath, lines);
        Debug.Log("Wrote scene validation report: " + reportPath);
    }

    private sealed class SceneResult
    {
        public string Path;
        public string Status;
        public int RootObjects;
        public int GameObjects;
        public int MissingScripts;
        public string Notes;

        public bool Passed => Status == "pass" || Status == "warning";
    }
}
